namespace WPCreatorWinForm
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(WPCreatorWinForm.Form1));
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.tb_nomdossier = new Bunifu.Framework.UI.BunifuMaterialTextbox();
            this.tb_nombdd = new Bunifu.Framework.UI.BunifuMaterialTextbox();
            this.label5 = new System.Windows.Forms.Label();
            this.tb_nomfichier = new Bunifu.Framework.UI.BunifuMaterialTextbox();
            this.tb_servername = new Bunifu.Framework.UI.BunifuMaterialTextbox();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.sw_servername = new Bunifu.Framework.UI.BunifuiOSSwitch();
            this.tb_pass = new Bunifu.Framework.UI.BunifuMaterialTextbox();
            this.labelmdp = new System.Windows.Forms.Label();
            this.tb_user = new Bunifu.Framework.UI.BunifuMaterialTextbox();
            this.tb_ip = new Bunifu.Framework.UI.BunifuMaterialTextbox();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.btn_testco = new Bunifu.Framework.UI.BunifuFlatButton();
            this.btn_creation = new Bunifu.Framework.UI.BunifuFlatButton();
            this.bunifuDragControl1 = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.btn_quit = new Bunifu.Framework.UI.BunifuFlatButton();
            this.btn_reduce = new Bunifu.Framework.UI.BunifuFlatButton();
            this.pg_etat = new Bunifu.Framework.UI.BunifuProgressBar();
            this.SuspendLayout();
            this.label1.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label1.Location = new System.Drawing.Point(489, 150);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(124, 31);
            this.label1.TabIndex = 0;
            this.label1.Text = "Nom du dossier du WP\r\n(après le /var/www/)\r\n";
            this.label2.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label2.Location = new System.Drawing.Point(489, 208);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(124, 28);
            this.label2.TabIndex = 1;
            this.label2.Text = "Nom de la base de de données MySQL\r\n";
            this.label3.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label3.Location = new System.Drawing.Point(489, 366);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(124, 28);
            this.label3.TabIndex = 2;
            this.label3.Text = "ServerName";
            this.label4.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label4.Location = new System.Drawing.Point(539, 327);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(124, 20);
            this.label4.TabIndex = 4;
            this.label4.Text = "ServerName ?";
            this.tb_nomdossier.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_nomdossier.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_nomdossier.characterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_nomdossier.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nomdossier.Font = new System.Drawing.Font("Century Gothic", 9.75F);
            this.tb_nomdossier.ForeColor = System.Drawing.Color.White;
            this.tb_nomdossier.HintForeColor = System.Drawing.Color.Empty;
            this.tb_nomdossier.HintText = "";
            this.tb_nomdossier.isPassword = false;
            this.tb_nomdossier.LineFocusedColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_nomdossier.LineIdleColor = System.Drawing.Color.White;
            this.tb_nomdossier.LineMouseHoverColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_nomdossier.LineThickness = 3;
            this.tb_nomdossier.Location = new System.Drawing.Point(637, 150);
            this.tb_nomdossier.Margin = new System.Windows.Forms.Padding(4);
            this.tb_nomdossier.MaxLength = 32767;
            this.tb_nomdossier.Name = "tb_nomdossier";
            this.tb_nomdossier.Size = new System.Drawing.Size(94, 31);
            this.tb_nomdossier.TabIndex = 5;
            this.tb_nomdossier.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_nombdd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_nombdd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_nombdd.characterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_nombdd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nombdd.Font = new System.Drawing.Font("Century Gothic", 9.75F);
            this.tb_nombdd.ForeColor = System.Drawing.Color.White;
            this.tb_nombdd.HintForeColor = System.Drawing.Color.Empty;
            this.tb_nombdd.HintText = "";
            this.tb_nombdd.isPassword = false;
            this.tb_nombdd.LineFocusedColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_nombdd.LineIdleColor = System.Drawing.Color.White;
            this.tb_nombdd.LineMouseHoverColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_nombdd.LineThickness = 3;
            this.tb_nombdd.Location = new System.Drawing.Point(637, 208);
            this.tb_nombdd.Margin = new System.Windows.Forms.Padding(4);
            this.tb_nombdd.MaxLength = 32767;
            this.tb_nombdd.Name = "tb_nombdd";
            this.tb_nombdd.Size = new System.Drawing.Size(94, 31);
            this.tb_nombdd.TabIndex = 6;
            this.tb_nombdd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.label5.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label5.Location = new System.Drawing.Point(489, 260);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(124, 28);
            this.label5.TabIndex = 7;
            this.label5.Text = "Nom du fichier de configuration Apache\r\n";
            this.tb_nomfichier.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_nomfichier.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_nomfichier.characterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_nomfichier.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_nomfichier.Font = new System.Drawing.Font("Century Gothic", 9.75F);
            this.tb_nomfichier.ForeColor = System.Drawing.Color.White;
            this.tb_nomfichier.HintForeColor = System.Drawing.Color.Empty;
            this.tb_nomfichier.HintText = "";
            this.tb_nomfichier.isPassword = false;
            this.tb_nomfichier.LineFocusedColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_nomfichier.LineIdleColor = System.Drawing.Color.White;
            this.tb_nomfichier.LineMouseHoverColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_nomfichier.LineThickness = 3;
            this.tb_nomfichier.Location = new System.Drawing.Point(637, 271);
            this.tb_nomfichier.Margin = new System.Windows.Forms.Padding(4);
            this.tb_nomfichier.MaxLength = 32767;
            this.tb_nomfichier.Name = "tb_nomfichier";
            this.tb_nomfichier.Size = new System.Drawing.Size(94, 31);
            this.tb_nomfichier.TabIndex = 8;
            this.tb_nomfichier.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_servername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_servername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_servername.characterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_servername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_servername.Font = new System.Drawing.Font("Century Gothic", 9.75F);
            this.tb_servername.ForeColor = System.Drawing.Color.White;
            this.tb_servername.HintForeColor = System.Drawing.Color.Empty;
            this.tb_servername.HintText = "";
            this.tb_servername.isPassword = false;
            this.tb_servername.LineFocusedColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_servername.LineIdleColor = System.Drawing.Color.White;
            this.tb_servername.LineMouseHoverColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_servername.LineThickness = 3;
            this.tb_servername.Location = new System.Drawing.Point(637, 366);
            this.tb_servername.Margin = new System.Windows.Forms.Padding(4);
            this.tb_servername.MaxLength = 32767;
            this.tb_servername.Name = "tb_servername";
            this.tb_servername.Size = new System.Drawing.Size(94, 31);
            this.tb_servername.TabIndex = 9;
            this.tb_servername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.label6.Font = new System.Drawing.Font("Montserrat Medium", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label6.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label6.Location = new System.Drawing.Point(183, 9);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(437, 54);
            this.label6.TabIndex = 10;
            this.label6.Text = "WordPress Creator\r\nv 0.1\r\n";
            this.label6.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.label7.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label7.Location = new System.Drawing.Point(262, 519);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(289, 30);
            this.label7.TabIndex = 11;
            this.label7.Text = "Copyright ® Thomas ROTSAERT, ouranet.com";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.sw_servername.BackColor = System.Drawing.Color.Transparent;
            this.sw_servername.BackgroundImage = ((System.Drawing.Image) (resources.GetObject("sw_servername.BackgroundImage")));
            this.sw_servername.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.sw_servername.Cursor = System.Windows.Forms.Cursors.Hand;
            this.sw_servername.Location = new System.Drawing.Point(489, 327);
            this.sw_servername.Name = "sw_servername";
            this.sw_servername.OffColor = System.Drawing.Color.Gray;
            this.sw_servername.OnColor = System.Drawing.Color.FromArgb(((int) (((byte) (71)))), ((int) (((byte) (202)))), ((int) (((byte) (94)))));
            this.sw_servername.Size = new System.Drawing.Size(35, 20);
            this.sw_servername.TabIndex = 12;
            this.sw_servername.Value = false;
            this.sw_servername.OnValueChange += new System.EventHandler(this.sw_servername_OnValueChange);
            this.tb_pass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_pass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_pass.characterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_pass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_pass.Font = new System.Drawing.Font("Century Gothic", 9.75F);
            this.tb_pass.ForeColor = System.Drawing.Color.White;
            this.tb_pass.HintForeColor = System.Drawing.Color.Empty;
            this.tb_pass.HintText = "";
            this.tb_pass.isPassword = true;
            this.tb_pass.LineFocusedColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_pass.LineIdleColor = System.Drawing.Color.White;
            this.tb_pass.LineMouseHoverColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_pass.LineThickness = 3;
            this.tb_pass.Location = new System.Drawing.Point(183, 271);
            this.tb_pass.Margin = new System.Windows.Forms.Padding(4);
            this.tb_pass.MaxLength = 32767;
            this.tb_pass.Name = "tb_pass";
            this.tb_pass.Size = new System.Drawing.Size(157, 31);
            this.tb_pass.TabIndex = 18;
            this.tb_pass.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.labelmdp.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.labelmdp.Location = new System.Drawing.Point(35, 260);
            this.labelmdp.Name = "labelmdp";
            this.labelmdp.Size = new System.Drawing.Size(124, 28);
            this.labelmdp.TabIndex = 17;
            this.labelmdp.Text = "Mot de passe";
            this.tb_user.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_user.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_user.BackColor = System.Drawing.SystemColors.Desktop;
            this.tb_user.characterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_user.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_user.Font = new System.Drawing.Font("Century Gothic", 9.75F);
            this.tb_user.ForeColor = System.Drawing.Color.White;
            this.tb_user.HintForeColor = System.Drawing.Color.Empty;
            this.tb_user.HintText = "";
            this.tb_user.isPassword = false;
            this.tb_user.LineFocusedColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_user.LineIdleColor = System.Drawing.Color.White;
            this.tb_user.LineMouseHoverColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_user.LineThickness = 3;
            this.tb_user.Location = new System.Drawing.Point(183, 208);
            this.tb_user.Margin = new System.Windows.Forms.Padding(4);
            this.tb_user.MaxLength = 32767;
            this.tb_user.Name = "tb_user";
            this.tb_user.Size = new System.Drawing.Size(157, 31);
            this.tb_user.TabIndex = 16;
            this.tb_user.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_ip.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_ip.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_ip.characterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_ip.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_ip.Font = new System.Drawing.Font("Century Gothic", 9.75F);
            this.tb_ip.ForeColor = System.Drawing.Color.White;
            this.tb_ip.HintForeColor = System.Drawing.Color.Empty;
            this.tb_ip.HintText = "";
            this.tb_ip.isPassword = false;
            this.tb_ip.LineFocusedColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_ip.LineIdleColor = System.Drawing.Color.White;
            this.tb_ip.LineMouseHoverColor = System.Drawing.Color.MediumSeaGreen;
            this.tb_ip.LineThickness = 3;
            this.tb_ip.Location = new System.Drawing.Point(183, 150);
            this.tb_ip.Margin = new System.Windows.Forms.Padding(4);
            this.tb_ip.MaxLength = 32767;
            this.tb_ip.Name = "tb_ip";
            this.tb_ip.Size = new System.Drawing.Size(157, 31);
            this.tb_ip.TabIndex = 15;
            this.tb_ip.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.label9.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label9.Location = new System.Drawing.Point(35, 208);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(124, 28);
            this.label9.TabIndex = 14;
            this.label9.Text = "Nom d\'utilisateur";
            this.label10.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label10.Location = new System.Drawing.Point(35, 150);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(124, 31);
            this.label10.TabIndex = 13;
            this.label10.Text = "Adresse IP du serveur";
            this.label8.Font = new System.Drawing.Font("Montserrat", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.label8.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label8.Location = new System.Drawing.Point(183, 63);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(437, 52);
            this.label8.TabIndex = 19;
            this.label8.Text = (("Assurez-vous que l\'utilisateur à les droits administrateur sur le serveur cible\r\n" + "" + "") + "");
            this.label8.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btn_testco.Active = false;
            this.btn_testco.Activecolor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_testco.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_testco.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btn_testco.BorderRadius = 0;
            this.btn_testco.ButtonText = "Tester la connexion";
            this.btn_testco.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btn_testco.DisabledColor = System.Drawing.Color.Gray;
            this.btn_testco.Iconcolor = System.Drawing.Color.Transparent;
            this.btn_testco.Iconimage = ((System.Drawing.Image) (resources.GetObject("btn_testco.Iconimage")));
            this.btn_testco.Iconimage_right = null;
            this.btn_testco.Iconimage_right_Selected = null;
            this.btn_testco.Iconimage_Selected = null;
            this.btn_testco.IconMarginLeft = 15;
            this.btn_testco.IconMarginRight = 15;
            this.btn_testco.IconRightVisible = true;
            this.btn_testco.IconRightZoom = 0D;
            this.btn_testco.IconVisible = true;
            this.btn_testco.IconZoom = 100D;
            this.btn_testco.IsTab = false;
            this.btn_testco.Location = new System.Drawing.Point(63, 346);
            this.btn_testco.Name = "btn_testco";
            this.btn_testco.Normalcolor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_testco.OnHovercolor = System.Drawing.Color.FromArgb(((int) (((byte) (36)))), ((int) (((byte) (129)))), ((int) (((byte) (77)))));
            this.btn_testco.OnHoverTextColor = System.Drawing.Color.White;
            this.btn_testco.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.btn_testco.selected = false;
            this.btn_testco.Size = new System.Drawing.Size(238, 29);
            this.btn_testco.TabIndex = 20;
            this.btn_testco.Text = "Tester la connexion";
            this.btn_testco.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_testco.Textcolor = System.Drawing.Color.White;
            this.btn_testco.TextFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btn_testco.Click += new System.EventHandler(this.btn_testco_Click);
            this.btn_creation.Active = false;
            this.btn_creation.Activecolor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_creation.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_creation.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btn_creation.BorderRadius = 0;
            this.btn_creation.ButtonText = "Créer le WordPress";
            this.btn_creation.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btn_creation.DisabledColor = System.Drawing.Color.Gray;
            this.btn_creation.Iconcolor = System.Drawing.Color.Transparent;
            this.btn_creation.Iconimage = ((System.Drawing.Image) (resources.GetObject("btn_creation.Iconimage")));
            this.btn_creation.Iconimage_right = null;
            this.btn_creation.Iconimage_right_Selected = null;
            this.btn_creation.Iconimage_Selected = null;
            this.btn_creation.IconMarginLeft = 0;
            this.btn_creation.IconMarginRight = 0;
            this.btn_creation.IconRightVisible = true;
            this.btn_creation.IconRightZoom = 0D;
            this.btn_creation.IconVisible = true;
            this.btn_creation.IconZoom = 90D;
            this.btn_creation.IsTab = false;
            this.btn_creation.Location = new System.Drawing.Point(503, 422);
            this.btn_creation.Name = "btn_creation";
            this.btn_creation.Normalcolor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_creation.OnHovercolor = System.Drawing.Color.FromArgb(((int) (((byte) (36)))), ((int) (((byte) (129)))), ((int) (((byte) (77)))));
            this.btn_creation.OnHoverTextColor = System.Drawing.Color.White;
            this.btn_creation.selected = false;
            this.btn_creation.Size = new System.Drawing.Size(237, 34);
            this.btn_creation.TabIndex = 21;
            this.btn_creation.Text = "Créer le WordPress";
            this.btn_creation.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_creation.Textcolor = System.Drawing.Color.White;
            this.btn_creation.TextFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btn_creation.Click += new System.EventHandler(this.btn_creation_Click);
            this.bunifuDragControl1.Fixed = true;
            this.bunifuDragControl1.Horizontal = true;
            this.bunifuDragControl1.TargetControl = this;
            this.bunifuDragControl1.Vertical = true;
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            this.btn_quit.Active = false;
            this.btn_quit.Activecolor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_quit.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_quit.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btn_quit.BorderRadius = 0;
            this.btn_quit.ButtonText = "";
            this.btn_quit.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btn_quit.DisabledColor = System.Drawing.Color.Gray;
            this.btn_quit.Iconcolor = System.Drawing.Color.Transparent;
            this.btn_quit.Iconimage = ((System.Drawing.Image) (resources.GetObject("btn_quit.Iconimage")));
            this.btn_quit.Iconimage_right = null;
            this.btn_quit.Iconimage_right_Selected = null;
            this.btn_quit.Iconimage_Selected = null;
            this.btn_quit.IconMarginLeft = 0;
            this.btn_quit.IconMarginRight = 0;
            this.btn_quit.IconRightVisible = true;
            this.btn_quit.IconRightZoom = 0D;
            this.btn_quit.IconVisible = true;
            this.btn_quit.IconZoom = 100D;
            this.btn_quit.IsTab = false;
            this.btn_quit.Location = new System.Drawing.Point(749, 13);
            this.btn_quit.Name = "btn_quit";
            this.btn_quit.Normalcolor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_quit.OnHovercolor = System.Drawing.Color.FromArgb(((int) (((byte) (36)))), ((int) (((byte) (129)))), ((int) (((byte) (77)))));
            this.btn_quit.OnHoverTextColor = System.Drawing.Color.White;
            this.btn_quit.selected = false;
            this.btn_quit.Size = new System.Drawing.Size(30, 31);
            this.btn_quit.TabIndex = 22;
            this.btn_quit.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_quit.Textcolor = System.Drawing.Color.White;
            this.btn_quit.TextFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btn_quit.Click += new System.EventHandler(this.btn_quit_Click);
            this.btn_reduce.Active = false;
            this.btn_reduce.Activecolor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_reduce.BackColor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_reduce.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btn_reduce.BorderRadius = 0;
            this.btn_reduce.ButtonText = "";
            this.btn_reduce.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btn_reduce.DisabledColor = System.Drawing.Color.Gray;
            this.btn_reduce.Iconcolor = System.Drawing.Color.Transparent;
            this.btn_reduce.Iconimage = ((System.Drawing.Image) (resources.GetObject("btn_reduce.Iconimage")));
            this.btn_reduce.Iconimage_right = null;
            this.btn_reduce.Iconimage_right_Selected = null;
            this.btn_reduce.Iconimage_Selected = null;
            this.btn_reduce.IconMarginLeft = 0;
            this.btn_reduce.IconMarginRight = 0;
            this.btn_reduce.IconRightVisible = true;
            this.btn_reduce.IconRightZoom = 0D;
            this.btn_reduce.IconVisible = true;
            this.btn_reduce.IconZoom = 100D;
            this.btn_reduce.IsTab = false;
            this.btn_reduce.Location = new System.Drawing.Point(710, 14);
            this.btn_reduce.Name = "btn_reduce";
            this.btn_reduce.Normalcolor = System.Drawing.Color.FromArgb(((int) (((byte) (46)))), ((int) (((byte) (139)))), ((int) (((byte) (87)))));
            this.btn_reduce.OnHovercolor = System.Drawing.Color.FromArgb(((int) (((byte) (36)))), ((int) (((byte) (129)))), ((int) (((byte) (77)))));
            this.btn_reduce.OnHoverTextColor = System.Drawing.Color.White;
            this.btn_reduce.selected = false;
            this.btn_reduce.Size = new System.Drawing.Size(30, 29);
            this.btn_reduce.TabIndex = 23;
            this.btn_reduce.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_reduce.Textcolor = System.Drawing.Color.White;
            this.btn_reduce.TextFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.btn_reduce.Click += new System.EventHandler(this.btn_reduce_Click);
            this.pg_etat.BackColor = System.Drawing.Color.Silver;
            this.pg_etat.BorderRadius = 5;
            this.pg_etat.Location = new System.Drawing.Point(499, 479);
            this.pg_etat.MaximumValue = 100;
            this.pg_etat.Name = "pg_etat";
            this.pg_etat.ProgressColor = System.Drawing.Color.MediumSeaGreen;
            this.pg_etat.Size = new System.Drawing.Size(231, 26);
            this.pg_etat.TabIndex = 24;
            this.pg_etat.Value = 0;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.Desktop;
            this.ClientSize = new System.Drawing.Size(800, 558);
            this.Controls.Add(this.pg_etat);
            this.Controls.Add(this.btn_reduce);
            this.Controls.Add(this.btn_quit);
            this.Controls.Add(this.btn_creation);
            this.Controls.Add(this.btn_testco);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.tb_pass);
            this.Controls.Add(this.labelmdp);
            this.Controls.Add(this.tb_user);
            this.Controls.Add(this.tb_ip);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.sw_servername);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.tb_servername);
            this.Controls.Add(this.tb_nomfichier);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.tb_nombdd);
            this.Controls.Add(this.tb_nomdossier);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form1";
            this.Text = "Form1";
            this.ResumeLayout(false);
        }

        private Bunifu.Framework.UI.BunifuFlatButton btn_creation;
        private Bunifu.Framework.UI.BunifuFlatButton btn_quit;
        private Bunifu.Framework.UI.BunifuFlatButton btn_reduce;
        private Bunifu.Framework.UI.BunifuFlatButton btn_testco;
        private Bunifu.Framework.UI.BunifuDragControl bunifuDragControl1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label labelmdp;
        public Bunifu.Framework.UI.BunifuProgressBar pg_etat;
        private Bunifu.Framework.UI.BunifuiOSSwitch sw_servername;
        private Bunifu.Framework.UI.BunifuMaterialTextbox tb_ip;
        public Bunifu.Framework.UI.BunifuMaterialTextbox tb_nombdd;
        public Bunifu.Framework.UI.BunifuMaterialTextbox tb_nomdossier;
        public Bunifu.Framework.UI.BunifuMaterialTextbox tb_nomfichier;
        private Bunifu.Framework.UI.BunifuMaterialTextbox tb_pass;
        private Bunifu.Framework.UI.BunifuMaterialTextbox tb_servername;
        private Bunifu.Framework.UI.BunifuMaterialTextbox tb_user;

        #endregion
    }
}